export interface Hashtag {
  tag: string;
  popularity: number; // 0-100 scale
  relevance: number; // 0-100 scale
}

export interface VideoData {
  id: string;
  title: string;
  platform: "TikTok" | "Instagram";
  url: string;
  thumbnailUrl: string;
  likes: number;
  shares: number;
  comments: number;
  views: number;
  likeToShareRatio: number;
  likeToCommentRatio: number;
  engagement: number; // overall engagement score
  publishedAt: string;
  duration: number; // in seconds
  hashtags: string[];
  categories: string[];
}

export interface ContentTheme {
  id: string;
  name: string;
  performance: number; // 0-100 scale
  videoCount: number;
  averageEngagement: number;
  topHashtags: string[];
}

export interface ContentFormat {
  id: string;
  name: string;
  performance: number; // 0-100 scale
  videoCount: number;
  averageEngagement: number;
  description: string;
}

export interface ContentIdea {
  id: string;
  title: string;
  description: string;
  suggestedHashtags: string[];
  estimatedPerformance: number; // 0-100 scale
  basedOnVideos: string[]; // IDs of videos this idea is based on
  format: string;
}

export interface AutoGeneratedContent {
  id: string;
  title: string;
  description: string;
  videoUrl: string; // Mock URL for the prototype
  thumbnailUrl: string;
  duration: number;
  suggestedHashtags: string[];
}

export interface ContentStrategyData {
  businessDescription: string;
  selectedHashtags: Hashtag[];
  totalVideosAnalyzed: number;
  contentThemes: ContentTheme[];
  contentFormats: ContentFormat[];
  contentIdeas: ContentIdea[];
  topVideos: VideoData[];
  autoGeneratedContent: AutoGeneratedContent[];
  scrapingStatus: {
    completed: boolean;
    progress: number; // 0-100 percent
    startedAt: string;
    completedAt?: string;
  };
}
