# name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Vercel CLI:
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_API_TOKEN }}
      - name: Copy Vercel Environment Variables
        run: vercel env pull ./client/.env.local --yes --environment=preview --token=${{ secrets.VERCEL_API_TOKEN }}

      # Build Project Artifacts
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_API_TOKEN }}

      # Deploy Project Artifacts to Vercel
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_API_TOKEN }}
