version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: deps # Stop at deps stage for development
    command: sh -c "cd apps/api && pnpm dev"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    env_file:
      - apps/api/.env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - supabase_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - supabase_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:

networks:
  supabase_network:
    external: true
    name: supabase_network_cursordevkit_octospark
