INSERT INTO public.posts (id, title, content, user_id, team_id, created_at, updated_at)
VALUES 
  (gen_random_uuid(), 'The Future of Web Development', 'As we look ahead to 2025, several trends are emerging in web development. React continues to dominate the frontend landscape, but Svelte and Solid are gaining traction for their performance benefits. WebAssembly is finally seeing mainstream adoption, enabling high-performance applications directly in the browser. Meanwhile, edge computing is transforming how we think about deployment and server architecture.', 'fd5e65e2-965a-4897-b6c2-07ea8f1adead', 'cd392e85-5f6d-4b54-abaa-4cbfe021939b', NOW(), NOW()),
  
  (gen_random_uuid(), 'Optimizing Database Performance', 'After months of troubleshooting, we''ve identified several key strategies for improving our PostgreSQL performance. Proper indexing made the biggest difference, reducing query times by 80% in some cases. We also implemented connection pooling and query caching, which helped with our high-traffic endpoints. The next step is exploring table partitioning for our logging tables.', 'ecd05012-57ea-40a1-8fca-112eb7aa44ab', 'cd392e85-5f6d-4b54-abaa-4cbfe021939b', NOW(), NOW()),
  
  (gen_random_uuid(), 'Redesigning Our Product Dashboard', 'Today we completed the redesign of our analytics dashboard. The new UI features a cleaner layout with improved data visualization components. We conducted usability testing with 12 participants and found that the new design reduced task completion time by 40%. Key improvements include the consolidated metrics panel and the new filtering system.', '2671bd53-3529-4ea7-b575-47ec87a77a10', 'eddda8d4-172e-42c6-bffe-685cb8a1eef6', NOW(), NOW()),
  
  (gen_random_uuid(), 'Q2 Marketing Campaign Results', 'Our Q2 digital marketing campaign exceeded expectations with a 24% increase in qualified leads. The video content performed particularly well, generating 3x more engagement than static images. Geographic targeting proved effective, with European markets showing the strongest response. We''ll be doubling down on video content for Q3 and expanding our presence in the German market.', '2671bd53-3529-4ea7-b575-47ec87a77a10', '6fbe972a-2f5d-4f5f-aab9-77684ae2a073', NOW(), NOW()),
  
  (gen_random_uuid(), 'Implementing CI/CD Pipelines', 'We recently overhauled our deployment process by implementing a robust CI/CD pipeline using GitHub Actions. The new system automatically runs tests, builds containers, and deploys to staging environments for every pull request. Production deployments now take 15 minutes instead of several hours, and we''ve reduced deployment-related incidents by 70%.', 'fd5e65e2-965a-4897-b6c2-07ea8f1adead', 'cd392e85-5f6d-4b54-abaa-4cbfe021939b', NOW(), NOW()),
  
  (gen_random_uuid(), 'User Research Findings', 'We just completed a comprehensive user research study involving 50 participants across different customer segments. Key findings include: 1) Users struggle with the notification settings, 2) The export feature is highly valued but difficult to discover, 3) Mobile users primarily use the app for monitoring rather than data entry. These insights will inform our product roadmap for the next quarter.', 'ecd05012-57ea-40a1-8fca-112eb7aa44ab', 'eddda8d4-172e-42c6-bffe-685cb8a1eef6', NOW(), NOW()),
  
  (gen_random_uuid(), 'Accessibility Improvements', 'Our recent accessibility audit identified several areas for improvement. We''ve implemented keyboard navigation throughout the application, improved screen reader compatibility, and enhanced color contrast ratios. All images now have proper alt text, and we''ve added ARIA labels to custom UI components. These changes have brought us to WCAG 2.1 AA compliance.', '2671bd53-3529-4ea7-b575-47ec87a77a10', 'eddda8d4-172e-42c6-bffe-685cb8a1eef6', NOW(), NOW()); 